### ISSUE TITLE
A minor bug

### ISSUE THREAD

**Issue by younghuman** [echen/restricted-boltzmann-machines#6]
The self.weight[0][0] should always be 0, and the bias unit in visual and hidden vectors should always be 1.
Can I collaborate with you on this project, I can help make some improvements like weight decay, mini-batch and persistent CD training.

**Comment by jsa41394** [comment]
Fork it? Also add if statement to  speed-up printout:

if(epoch % 100 == 0):
        print("Epoch %s: error is %s" % (epoch, error))

**Comment by 1230pitchanqw** [comment]
Thanks for the posting.
I am a little confuse about this model, can someone help me out of here:
Why do we compute this: "pos_hidden_states = pos_hidden_probs > np.random.rand(num_examples, self.num_hidden + 1)"

In the article, it was saying "for the jth hidden unit, compute its activation energy a_j=∑_iw_ijx_i, and set x_j to 1 with probability σ(a_j) and to 0 with probability 1−σ(a_j)."

Why we compare it with random number? 
@younghuman @jsa41394 @echen @vi 
Thanks!

**Comment by jsa41394** [comment]
The comparison with a random number is the "set as 0 or 1 part". It's a stochastic model, which means you need to simulate binary states using randomness. In computers, you can do that by sampling from a random (uniform) distribution. So, for e.g., you simulate a 50% chance coin toss with: toss = .5 > random.random(), where random.random returns a float between 0 and 1.

**Comment by jsa41394** [comment]
Numpy returns random floats in a matrix, fyi. Always look up documentation

**Comment by 1230pitchanqw** [comment]
@jsa41394 Thanks! After a few days thinking I think I understand it now, stochastic approach.
thank you

**Comment by echen** [comment]
Sorry for the incredible lack of response! I think I missed all the Github notifications here.

@younghuman I assume you've moved on to something else :), but if for whatever reason you're still interested, I'm happy to add you as a collaborator or merge any forks in.
